// This file is part of example-shielded-chips.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This example ships TWO contracts: chips.compact (a MIP-0011 native shielded
// token) and roulette.compact (a game that custodies and pays out coins of that
// token's color). Each compiles to its own contract/managed/<name> directory
// (generated by `yarn compile`, gitignored), so each gets its own exports,
// zk-config path, and CompiledContract below.
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';

export {
  Contract as RouletteContract,
  ledger as rouletteLedger,
  pureCircuits as roulettePureCircuits,
  BetState,
  Color,
  type Ledger as RouletteLedger,
  type ImpureCircuits as RouletteImpureCircuits,
} from './managed/roulette/contract/index.js';

export {
  Contract as ChipsContract,
  ledger as chipsLedger,
  pureCircuits as chipsPureCircuits,
  type Ledger as ChipsLedger,
  type ImpureCircuits as ChipsImpureCircuits,
} from './managed/chips/contract/index.js';

import { rouletteWitnesses, chipsWitnesses } from './witnesses.js';
import { Contract as RouletteContractClass } from './managed/roulette/contract/index.js';
import { Contract as ChipsContractClass } from './managed/chips/contract/index.js';

const currentDir = path.resolve(new URL(import.meta.url).pathname, '..');
export const rouletteZkConfigPath = path.resolve(currentDir, 'managed', 'roulette');
export const chipsZkConfigPath = path.resolve(currentDir, 'managed', 'chips');

export const CompiledRouletteContract = CompiledContract.make(
  'RouletteContract',
  RouletteContractClass,
).pipe(
  CompiledContract.withWitnesses(rouletteWitnesses),
  CompiledContract.withCompiledFileAssets(rouletteZkConfigPath),
);

export const CompiledChipsContract = CompiledContract.make(
  'ChipsContract',
  ChipsContractClass,
).pipe(
  CompiledContract.withWitnesses(chipsWitnesses),
  CompiledContract.withCompiledFileAssets(chipsZkConfigPath),
);
