// Browser-side handle on the compiled token-transfers contract.
//
// Generated by `yarn new:ui` from
// contract/managed/token-transfers/compiler/contract-info.json. This file is
// template-owned: change templates/ui/src/midnight/contract.ts, not this copy
// (`yarn new:ui --check <name>` fails CI when they diverge).
//
// examples/token-transfers/contract/index.ts can't be reused here: it imports
// `node:path` to build an absolute zkConfigPath for NodeZkConfigProvider. The
// compiler's generated JS (contract/managed/token-transfers/contract/index.js) is
// plain ESM with no Node dependencies, so we import it directly. Run
// `yarn compile` in examples/token-transfers first; the managed/ output is
// gitignored.
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import {
  Contract,
  ledger,
  pureCircuits,
  type Ledger,
} from "../../../contract/managed/token-transfers/contract/index.js";
import type { PrivateStateStorage } from "./private-state";

// pureCircuits run locally with no proof and no tx (e.g. deriving a public
// key from a secret to find "which player am I" on the ledger).
export { Contract, ledger, pureCircuits, type Ledger };

/** Every provable circuit, i.e. every ZK key set copy-zk.mjs serves. */
export type TokenTransfersCircuits = "mintAndReceive" | "sendToUser" | "receiveTokens" | "receiveNightTokens" | "sendNightTokensToUser" | "receiveShieldedTokens" | "sendShieldedToUser" | "mintShieldedToSelf" | "mintAndSendShielded";

/**
 * The contract declares no witnesses, so there is no private state.
 * deployContract still wants a private-state id and an initial value, as
 * in the Node test, so we store an empty object.
 */
export type TokenTransfersPrivateState = Record<string, never>;
export const createInitialPrivateState = (): TokenTransfersPrivateState => ({});
export const PRIVATE_STATE_ID = "tokenTransfersPrivateState";

/**
 * Where private state is kept (`yarn new:ui --private-state`, recorded in
 * ui/new-ui.json): in memory, so a reload
 * loses it.
 */
export const PRIVATE_STATE_STORAGE: PrivateStateStorage = "memory";

/** Where copy-zk.mjs puts the keys and zkir, relative to the page origin. */
export const ZK_ASSETS_PATH = "managed/token-transfers";

/**
 * Same construction as CompiledTokenTransfersContract in contract/index.ts:
 *  - withVacantWitnesses: the contract declares no witnesses.
 *  - withCompiledFileAssets: required by the type, so the result is a fully
 *    configured CompiledContract. In the browser, midnight-js-contracts gets
 *    verifier/prover keys and ZKIR from `providers.zkConfigProvider`
 *    (a FetchZkConfigProvider pointed at ZK_ASSETS_PATH), not from this path.
 */
export const CompiledTokenTransfersContract = CompiledContract.make(
  "TokenTransfersContract",
  Contract,
).pipe(
  CompiledContract.withVacantWitnesses,
  CompiledContract.withCompiledFileAssets(ZK_ASSETS_PATH),
);
