// This file is part of example-__name__.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file's main purpose is to export the compiled contract. The imports below
// resolve against contract/managed/__name__, which is generated by `yarn compile`
// (gitignored). Write contract/__name__.compact first, then compile.
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';

export {
  Contract,
  ledger,
  pureCircuits,
  type Witnesses,
  type Ledger,
  type ImpureCircuits,
  type PureCircuits,
} from './managed/__name__/contract/index.js';
import { Contract } from './managed/__name__/contract/index.js';
__WITNESS_IMPORT__
const currentDir = path.resolve(new URL(import.meta.url).pathname, '..');
export const zkConfigPath = path.resolve(currentDir, 'managed', '__name__');

export const Compiled__Name__Contract = CompiledContract.make(
  '__Name__Contract',
  Contract,
).pipe(
  CompiledContract.__WITNESS_METHOD__,
  CompiledContract.withCompiledFileAssets(zkConfigPath),
);
