// Browser-side handle on the compiled battleship contract.
//
// Generated by `yarn new:ui` from
// contract/managed/battleship/compiler/contract-info.json. This file is
// template-owned: change templates/ui/src/midnight/contract.ts, not this copy
// (`yarn new:ui --check <name>` fails CI when they diverge).
//
// examples/battleship/contract/index.ts can't be reused here: it imports
// `node:path` to build an absolute zkConfigPath for NodeZkConfigProvider. The
// compiler's generated JS (contract/managed/battleship/contract/index.js) is
// plain ESM with no Node dependencies, so we import it directly. Run
// `yarn compile` in examples/battleship first; the managed/ output is
// gitignored.
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import {
  Contract,
  ledger,
  pureCircuits,
  type Ledger,
} from "../../../contract/managed/battleship/contract/index.js";
import { createBattlePrivateState, witnesses } from "../../../contract/witnesses.js";
import type { PrivateStateStorage } from "./private-state";

// pureCircuits run locally with no proof and no tx (e.g. deriving a public
// key from a secret to find "which player am I" on the ledger).
export { Contract, ledger, pureCircuits, type Ledger };

/** Every provable circuit, i.e. every ZK key set copy-zk.mjs serves. */
export type BattleshipCircuits = "acceptGame" | "player1Shoot" | "player2Shoot" | "checkBoard1" | "checkBoard2";

/**
 * Private state is whatever examples/battleship/contract/witnesses.ts builds.
 * PRIVATE_STATE_STORAGE below says where it is kept (./private-state.ts).
 */
export type BattleshipPrivateState = ReturnType<typeof createBattlePrivateState>;
export const createInitialPrivateState = createBattlePrivateState;
export const PRIVATE_STATE_ID = "battleshipPrivateState";

/**
 * Where private state is kept (`yarn new:ui --private-state`, recorded in
 * ui/new-ui.json): encrypted in IndexedDB,
 * unlocked by a passphrase each session, so it survives reloads.
 */
export const PRIVATE_STATE_STORAGE: PrivateStateStorage = "persistent";

/** Where copy-zk.mjs puts the keys and zkir, relative to the page origin. */
export const ZK_ASSETS_PATH = "managed/battleship";

/**
 * Same construction as CompiledBattleshipContract in contract/index.ts:
 *  - withWitnesses: the TypeScript witnesses from contract/witnesses.ts.
 *  - withCompiledFileAssets: required by the type, so the result is a fully
 *    configured CompiledContract. In the browser, midnight-js-contracts gets
 *    verifier/prover keys and ZKIR from `providers.zkConfigProvider`
 *    (a FetchZkConfigProvider pointed at ZK_ASSETS_PATH), not from this path.
 */
export const CompiledBattleshipContract = CompiledContract.make(
  "BattleshipContract",
  Contract,
).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(ZK_ASSETS_PATH),
);
