// The calculator flow: deploy or join (the generic DeploymentCard), then watch
// the public `result` ledger field and call the five circuits.
//
// Seed file: generated by `yarn new:ui`, then replaced with the calculator UI.
// The drift check ignores it.
import { useMemo, useState } from "react";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { DeploymentCard } from "@/components/deployment-card";
import { useContractState } from "@/hooks/use-contract-state";
import { useDeployment } from "@/hooks/use-deployment";
import {
  deployCalculator,
  evaluate,
  joinCalculator,
  OPERATIONS,
  parseOperand,
  result$,
  type Operation,
} from "@/midnight/calculator-api";

export function CalculatorPanel() {
  const deployment = useDeployment({ deploy: deployCalculator, join: joinCalculator });
  const { providers, contract, address, busy, error, run } = deployment;

  const resultObservable = useMemo(
    () => (providers && address ? result$(providers, address) : null),
    [providers, address],
  );
  const { state: result, error: stateError } = useContractState(resultObservable);

  return (
    <div className="flex flex-col gap-6">
      <DeploymentCard deployment={deployment} />

      {providers && address && (
        <>
          <Card>
            <CardHeader>
              <CardTitle>2. Result</CardTitle>
              <CardDescription>
                The public <code>result</code> ledger field, streamed live from the indexer. Every
                operation overwrites it.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="font-mono text-4xl tabular-nums" data-testid="on-chain-result">
                {result === null ? (
                  <span className="text-base text-muted-foreground">Loading...</span>
                ) : (
                  result.toString()
                )}
              </p>
              {stateError && <p className="text-xs text-destructive">{stateError.message}</p>}
            </CardContent>
          </Card>

          <OperationsCard
            busy={busy}
            disabled={busy !== null || !contract}
            onRun={(op, a, b) =>
              run(op, async () => {
                if (!contract) return;
                await OPERATIONS[op].call(contract, a, b);
              })
            }
          />
        </>
      )}

      {error && <p className="text-sm text-destructive">{error}</p>}
    </div>
  );
}

/**
 * Two operand fields and one button per circuit. Each button previews what the
 * contract would store, and is disabled with the reason when the circuit
 * would reject the inputs (see `evaluate`).
 */
export function OperationsCard({
  busy,
  disabled,
  onRun,
}: {
  busy: string | null;
  disabled: boolean;
  onRun: (op: Operation, a: bigint, b: bigint) => void;
}) {
  const [aText, setAText] = useState("20");
  const [bText, setBText] = useState("6");
  const a = parseOperand(aText);
  const b = parseOperand(bText);

  return (
    <Card>
      <CardHeader>
        <CardTitle>3. Operations</CardTitle>
        <CardDescription>
          Each button runs one circuit and stores its result on chain. Operands and results are{" "}
          <code>Uint&lt;16&gt;</code> (0 to 65535). <code>divide</code> computes the quotient
          off-chain in the <code>divMod</code> witness, and the circuit only checks it.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <div className="grid grid-cols-2 gap-2">
          <Input
            aria-label="num1"
            inputMode="numeric"
            value={aText}
            onChange={(e) => setAText(e.target.value)}
          />
          <Input
            aria-label="num2"
            inputMode="numeric"
            value={bText}
            onChange={(e) => setBText(e.target.value)}
          />
        </div>

        <ul className="flex flex-col gap-2">
          {(Object.keys(OPERATIONS) as Operation[]).map((op) => {
            const { symbol, arity } = OPERATIONS[op];
            const operandsOk = a !== null && (arity === 1 || b !== null);
            const outcome = operandsOk
              ? evaluate(op, a, b ?? 0n)
              : ({ ok: false, reason: "enter whole numbers" } as const);
            const expr = arity === 1 ? `${aText.trim()}²` : `${aText.trim()} ${symbol} ${bText.trim()}`;
            return (
              <li key={op} className="flex items-center gap-3">
                <Button
                  className="w-28"
                  disabled={disabled || !outcome.ok}
                  onClick={() => outcome.ok && onRun(op, a!, b ?? 0n)}
                >
                  {busy === op && <Loader2 className="animate-spin" />}
                  {op}
                </Button>
                <span
                  className={outcome.ok ? "font-mono text-sm" : "text-sm text-muted-foreground"}
                  data-testid={`preview-${op}`}
                >
                  {outcome.ok ? `${expr} = ${outcome.value}` : outcome.reason}
                </span>
              </li>
            );
          })}
        </ul>

        {busy !== null && busy in OPERATIONS && (
          <p className="text-xs text-muted-foreground">
            Running the circuit, proving, then waiting for wallet approval and finalization.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
