// This file is part of mn-examples.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Per-UI verification status, for new-ui.mjs. Zero dependencies.
//
// CI proves a generated UI installs, typechecks, passes its unit tests and
// builds. It can't prove the rest: the page running in a real browser, and
// deploys and circuit calls approved in Lace. Those are run by a person, and
// recorded in examples/<name>/ui/verification.json (author-owned, created by
// `yarn new:ui` with every step "not-run"):
//
//   { "steps": { "<step>": { "status": "verified" | "partial" | "not-run",
//                             "date": "YYYY-MM-DD",   // when it was run
//                             "notes": "what exactly ran" } } }
//
// templates/ui/VERIFIED.md shows them as one table. The table sits between
// two markers and is generated: `--sync` rewrites it, and `--check` fails when
// it's stale, when a verification.json is malformed, or when it claims the
// Lace circuit calls are verified while ui/README.md still has its
// "TODO: end-to-end verification with Lace" checklist.

import fs from 'node:fs';
import path from 'node:path';

/** The steps CI doesn't run, in the verification checklist's order. */
export const STEPS = [
  { key: 'browser', title: 'In Chrome, no wallet (step 6)' },
  { key: 'laceDeploy', title: 'Lace deploy (step 7)' },
  { key: 'laceCalls', title: 'Lace circuit calls (step 7)' },
  { key: 'preprod', title: 'preprod' },
];
const STATUS_MARK = { verified: '✅', partial: '◐', 'not-run': '—' };
export const VERIFICATION_FILE = 'verification.json';
const BEGIN = '<!-- BEGIN generated by `yarn new:ui` from examples/*/ui/verification.json; do not edit -->';
const END = '<!-- END generated -->';
const LACE_TODO = 'TODO: end-to-end verification with Lace';
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** Problems with one UI's verification.json (empty when it's valid). */
export function validate(json, name) {
  const where = `examples/${name}/ui/${VERIFICATION_FILE}`;
  if (typeof json !== 'object' || json === null || typeof json.steps !== 'object' || json.steps === null) {
    return [`${where}: needs a "steps" object`];
  }
  const errors = [];
  const known = new Set(STEPS.map((s) => s.key));
  for (const key of Object.keys(json.steps)) {
    if (!known.has(key)) errors.push(`${where}: unknown step "${key}" (known: ${[...known].join(', ')})`);
  }
  for (const { key } of STEPS) {
    const step = json.steps[key];
    if (!step) {
      errors.push(`${where}: missing step "${key}"`);
      continue;
    }
    if (!(step.status in STATUS_MARK)) {
      errors.push(`${where}: ${key}.status must be one of ${Object.keys(STATUS_MARK).join(', ')}`);
    }
    if (step.status !== 'not-run') {
      if (!DATE_RE.test(step.date ?? '')) errors.push(`${where}: ${key} was run, so it needs a "date" (YYYY-MM-DD)`);
      if (typeof step.notes !== 'string' || step.notes.trim() === '') {
        errors.push(`${where}: ${key} was run, so it needs "notes" saying exactly what ran`);
      }
    }
  }
  return errors;
}

/**
 * Read and validate every UI's verification.json. Returns the parsed entries
 * and every problem found, including a claim the UI's README contradicts.
 */
export function readAll(examplesDir, names) {
  const entries = [];
  const errors = [];
  for (const name of names) {
    const file = path.join(examplesDir, name, 'ui', VERIFICATION_FILE);
    if (!fs.existsSync(file)) {
      errors.push(`examples/${name}/ui/${VERIFICATION_FILE}: missing (\`yarn new:ui ${name} --sync\` creates one)`);
      continue;
    }
    let json;
    try {
      json = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      errors.push(`examples/${name}/ui/${VERIFICATION_FILE}: not valid JSON (${e.message})`);
      continue;
    }
    const problems = validate(json, name);
    errors.push(...problems);
    if (problems.length) continue;
    const readme = path.join(examplesDir, name, 'ui', 'README.md');
    if (json.steps.laceCalls.status === 'verified' && fs.existsSync(readme)) {
      if (fs.readFileSync(readme, 'utf8').includes(LACE_TODO)) {
        errors.push(
          `examples/${name}/ui/${VERIFICATION_FILE}: laceCalls is "verified", but ui/README.md still has ` +
            `"${LACE_TODO}". Tick the checklist off and delete it, or lower the status.`,
        );
      }
    }
    entries.push({ name, steps: json.steps });
  }
  return { entries, errors };
}

/** The generated block: a table plus one numbered note per step that ran. */
export function renderBlock(entries) {
  const notes = [];
  const cell = (step) => {
    const mark = STATUS_MARK[step.status];
    if (step.status === 'not-run') return mark;
    notes.push(`${step.date}: ${step.notes.trim().replace(/\s*\n\s*/g, ' ')}`);
    return `${mark} ${notes.length}`;
  };
  const rows = entries.map(({ name, steps }) => `| ${name} | ${STEPS.map(({ key }) => cell(steps[key])).join(' | ')} |`);
  return [
    BEGIN,
    '',
    `| UI | ${STEPS.map((s) => s.title).join(' | ')} |`,
    `|---|${STEPS.map(() => '---|').join('')}`,
    ...rows,
    '',
    '✅ verified · ◐ partly verified (see its note) · — not run',
    '',
    ...notes.map((n, i) => `${i + 1}. ${n}`),
    '',
    END,
  ].join('\n');
}

/** `doc` with its generated block replaced, or null when it has no markers. */
export function withBlock(doc, block) {
  const start = doc.indexOf(BEGIN);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1 || end < start) return null;
  return doc.slice(0, start) + block + doc.slice(end + END.length);
}

/** The skeleton a new UI starts with: every step not run yet. */
export function skeleton() {
  return `${JSON.stringify({ steps: Object.fromEntries(STEPS.map(({ key }) => [key, { status: 'not-run' }])) }, null, 2)}\n`;
}
