// Mint the four remote test wallets and write them to the repo-root
// .env.<network>, then print their addresses for manual faucet funding.
//
// ORDER MATTERS: run `yarn preseed:cut` BEFORE this. Fast-sync may only seed a
// wallet whose birthday is at or after the reference bundle's height, so a
// bundle cut after these wallets are minted makes them un-seedable and every
// run silently pays the full ~78-minute genesis sync. See FAST-SYNC.md.

import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { WalletSeeds } from '@midnight-ntwrk/testkit-js';
import { createKeystore } from '@midnight-ntwrk/wallet-sdk/unshielded';
import {
  getChainTipHeight,
  getConfig,
  loadReferenceBundle,
  REFERENCE_ROOT,
  type CanonicalRole,
} from '../src/index.js';

const ROLES: CanonicalRole[] = ['ALICE', 'BOB', 'CHARLIE', 'DAVE'];

const network = process.env['MIDNIGHT_NETWORK'] ?? 'preprod';
const force = process.argv.includes('--force');
const config = getConfig(network);

if (network === 'local') {
  throw new Error('Local runs use the genesis seeds; there is nothing to generate.');
}

setNetworkId(config.networkId);

const envPath = fileURLToPath(new URL(`../../../.env.${network}`, import.meta.url));
if (existsSync(envPath) && !force) {
  throw new Error(
    `${envPath} already exists. These seeds are the ONLY copy of those wallets — ` +
      're-run with --force only if you are certain you want to discard them.',
  );
}

const tip = await getChainTipHeight(config.indexer);
if (tip === undefined) {
  throw new Error(`Could not read the ${network} chain tip from ${config.indexer}.`);
}

// Warn loudly if the reference is newer than the wallets we are about to mint:
// that is the cut-after-generate mistake, and it fails silently at run time.
const reference = loadReferenceBundle(REFERENCE_ROOT, config.networkId);
if (reference && reference.height > tip) {
  throw new Error(
    `The ${config.networkId} reference bundle is at height ${reference.height}, ahead of the ` +
      `chain tip ${tip}. These wallets could never be fast-synced from it.`,
  );
}

interface Minted {
  role: CanonicalRole;
  seed: string;
  address: string;
}

const minted: Minted[] = ROLES.map((role) => {
  const seed = randomBytes(32).toString('hex');
  const keystore = createKeystore(WalletSeeds.fromMasterSeed(seed).unshielded, config.networkId);
  return { role, seed, address: String(keystore.getBech32Address()) };
});

const lines = [
  `# ${network} test wallets — generated by \`yarn wallets:new\` on ${new Date().toISOString()}`,
  '#',
  '# These seeds are secrets and this file is gitignored. It is the only copy.',
  '#',
  '# The _BIRTHDAY lines record the chain tip at the moment each seed was minted.',
  '# They are what lets these wallets fast-sync from the shipped reference bundle',
  '# instead of walking the chain from genesis. NEVER hand-write a _BIRTHDAY next',
  '# to a pre-existing wallet: it defeats the safety guard and can silently hide',
  '# that wallet\'s funds. See FAST-SYNC.md.',
  '',
];
for (const { role, seed, address } of minted) {
  if (role === 'DAVE') {
    lines.push(
      '# Dave: fund with tNIGHT but do NOT delegate DUST — the sponsorship suite',
      '# needs a wallet whose fees Alice pays. See examples/private-party/docs/SPONSORSHIP.md.',
    );
  }
  lines.push(`# ${role} ${address}`);
  lines.push(`MIDNIGHT_${network.toUpperCase()}_${role}_SEED=${seed}`);
  lines.push(`MIDNIGHT_${network.toUpperCase()}_${role}_BIRTHDAY=${tip}`);
  lines.push('');
}
writeFileSync(envPath, `${lines.join('\n')}`, { mode: 0o600 });

const bar = '='.repeat(72);
console.log(`\n${bar}`);
console.log(`Wrote 4 ${network} wallets to ${envPath} (birthday ${tip})`);
console.log(bar);
console.log(`\nFund these at the faucet:\n  ${config.faucet}\n`);
for (const { role, address } of minted) {
  const note = role === 'DAVE' ? '  <-- tNIGHT ONLY, do NOT delegate DUST' : '';
  console.log(`  ${role.padEnd(8)} ${address}${note}`);
}
console.log(
  '\nAlice, Bob and Charlie need tNIGHT; the suites register their NIGHT for DUST',
  '\nautomatically on first run. Dave needs tNIGHT and nothing else.',
);
console.log(`\nThen: yarn test:${network}\n${bar}\n`);
