// Browser-side handle on the compiled __name__ contract.
//
// Generated by `yarn new:ui` from
// contract/managed/__MANAGED__/compiler/contract-info.json. This file is
// template-owned: change templates/ui/src/midnight/contract.ts, not this copy
// (`yarn new:ui --check <name>` fails CI when they diverge).
//
// examples/__name__/contract/index.ts can't be reused here: it imports
// `node:path` to build an absolute zkConfigPath for NodeZkConfigProvider. The
// compiler's generated JS (contract/managed/__MANAGED__/contract/index.js) is
// plain ESM with no Node dependencies, so we import it directly. Run
// `yarn compile` in examples/__name__ first; the managed/ output is
// gitignored.
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import {
  Contract,
  ledger,
  pureCircuits,
  type Ledger,
} from "../../../contract/managed/__MANAGED__/contract/index.js";
__WITNESS_IMPORT__
import type { PrivateStateStorage } from "./private-state";

// pureCircuits run locally with no proof and no tx (e.g. deriving a public
// key from a secret to find "which player am I" on the ledger).
export { Contract, ledger, pureCircuits, type Ledger };

/** Every provable circuit, i.e. every ZK key set copy-zk.mjs serves. */
export type __Name__Circuits = __CIRCUIT_UNION__;

__PRIVATE_STATE_BLOCK__
export const PRIVATE_STATE_ID = "__camelName__PrivateState";

/**
 * Where private state is kept (`yarn new:ui --private-state`, recorded in
 * ui/new-ui.json): __PRIVATE_STATE_STORAGE_DOC__
 */
export const PRIVATE_STATE_STORAGE: PrivateStateStorage = "__PRIVATE_STATE_STORAGE__";

/** Where copy-zk.mjs puts the keys and zkir, relative to the page origin. */
export const ZK_ASSETS_PATH = "managed/__MANAGED__";

/**
 * Same construction as Compiled__Name__Contract in contract/index.ts:
 *  - __WITNESS_METHOD_DOC__
 *  - withCompiledFileAssets: required by the type, so the result is a fully
 *    configured CompiledContract. In the browser, midnight-js-contracts gets
 *    verifier/prover keys and ZKIR from `providers.zkConfigProvider`
 *    (a FetchZkConfigProvider pointed at ZK_ASSETS_PATH), not from this path.
 */
export const Compiled__Name__Contract = CompiledContract.make(
  "__Name__Contract",
  Contract,
).pipe(
  CompiledContract.__WITNESS_METHOD__,
  CompiledContract.withCompiledFileAssets(ZK_ASSETS_PATH),
);
