// Contract operations the UI calls. Each one is the browser counterpart of a
// step in the Node test (examples/calculator/src/test/calculator.test.ts); the
// only difference is where `providers` came from.
//
// Seed file: generated by `yarn new:ui`, then extended for the calculator with
// `result$` and the OPERATIONS table / `evaluate` that the panel uses to
// pre-check operands. The drift check ignores it.
import {
  deployContract,
  findDeployedContract,
  type FoundContract,
} from "@midnight-ntwrk/midnight-js-contracts";
import type { ContractAddress } from "@midnight-ntwrk/midnight-js-protocol/compact-runtime";
import { map, type Observable } from "rxjs";
import {
  CompiledCalculatorContract,
  createInitialPrivateState,
  ledger,
  PRIVATE_STATE_ID,
  type Contract,
  type Ledger,
} from "./contract";
import type { CalculatorProviders } from "./providers";

export type CalculatorContract = FoundContract<Contract>;

/**
 * Deploy a fresh calculator contract. The wallet is asked to balance and sign
 * the deploy tx.
 */
export async function deployCalculator(
  providers: CalculatorProviders,
): Promise<{ contract: CalculatorContract; address: ContractAddress }> {
  const deployed = await deployContract(providers, {
    compiledContract: CompiledCalculatorContract,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: createInitialPrivateState(),
  });
  return {
    contract: deployed,
    address: deployed.deployTxData.public.contractAddress,
  };
}

/**
 * Attach to an existing deployment by address. findDeployedContract fetches
 * the on-chain state and checks that its verifier keys match the ones we serve
 * (a wrong address or a different contract fails here, before any tx).
 */
export async function joinCalculator(
  providers: CalculatorProviders,
  address: ContractAddress,
): Promise<CalculatorContract> {
  return findDeployedContract(providers, {
    compiledContract: CompiledCalculatorContract,
    contractAddress: address,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: createInitialPrivateState(),
  });
}

// One wrapper per provable circuit. midnight-js runs the circuit locally,
// proves it (wallet or proof server), then gets the wallet to balance and
// submit it. Each resolves once the tx is final on chain.

/**
 * A circuit's arguments without its leading CircuitContext, i.e. what
 * `contract.callTx.<circuit>(...)` takes. Not `Parameters<callTx[c]>`: callTx
 * members are overloaded, and `Parameters` picks the last overload, whose
 * first parameter is a TransactionContext.
 */
type CircuitArgs<K extends keyof Contract["provableCircuits"]> =
  Parameters<Contract["provableCircuits"][K]> extends [unknown, ...infer A] ? A : never;

/** Circuit `add(num1, num2)`. */
export async function add(
  contract: CalculatorContract,
  ...args: CircuitArgs<"add">
) {
  return contract.callTx.add(...args);
}

/** Circuit `subtract(num1, num2)`. */
export async function subtract(
  contract: CalculatorContract,
  ...args: CircuitArgs<"subtract">
) {
  return contract.callTx.subtract(...args);
}

/** Circuit `multiply(num1, num2)`. */
export async function multiply(
  contract: CalculatorContract,
  ...args: CircuitArgs<"multiply">
) {
  return contract.callTx.multiply(...args);
}

/** Circuit `square(num1)`. */
export async function square(
  contract: CalculatorContract,
  ...args: CircuitArgs<"square">
) {
  return contract.callTx.square(...args);
}

/** Circuit `divide(num1, num2)`. */
export async function divide(
  contract: CalculatorContract,
  ...args: CircuitArgs<"divide">
) {
  return contract.callTx.divide(...args);
}

/**
 * Live view of the public `result` ledger field (a Uint<16>, so a bigint in
 * 0..65535). It is 0 right after deploy and holds the last operation's result.
 */
export function result$(
  providers: CalculatorProviders,
  address: ContractAddress,
): Observable<bigint> {
  return ledger$(providers, address).pipe(map((l) => l.result));
}

// --- operand checks -----------------------------------------------------------
//
// Every operand and every result is a Uint<16>. The contract enforces that
// while midnight-js runs the circuit locally, before anything is proven or sent
// to the wallet, so a bad input never costs a wallet prompt. It does fail with a
// raw runtime message, though (e.g. "cast from Field or Uint value to smaller
// Uint value failed: 65536 is greater than 65535"). `evaluate` mirrors those
// rules so the panel can explain the problem and disable the button instead.
// src/__tests__/calculator-circuits.test.ts checks it against the real circuits.

/** Largest value a Compact `Uint<16>` holds (contract-info.json: maxval). */
export const UINT16_MAX = 65535n;

export type Operation = "add" | "subtract" | "multiply" | "square" | "divide";

export interface OperationInfo {
  /** Button label. */
  symbol: string;
  /** `square` takes one operand, everything else two. */
  arity: 1 | 2;
  /** The wrapper above that submits the circuit. */
  call: (contract: CalculatorContract, a: bigint, b: bigint) => Promise<unknown>;
}

export const OPERATIONS: Record<Operation, OperationInfo> = {
  add: { symbol: "+", arity: 2, call: (c, a, b) => add(c, a, b) },
  subtract: { symbol: "−", arity: 2, call: (c, a, b) => subtract(c, a, b) },
  multiply: { symbol: "×", arity: 2, call: (c, a, b) => multiply(c, a, b) },
  square: { symbol: "x²", arity: 1, call: (c, a) => square(c, a) },
  divide: { symbol: "÷", arity: 2, call: (c, a, b) => divide(c, a, b) },
};

export type Evaluation = { ok: true; value: bigint } | { ok: false; reason: string };

/**
 * What the contract would store in `result` for `op(a, b)`, or why the circuit
 * would reject it. `b` is ignored for `square`.
 */
export function evaluate(op: Operation, a: bigint, b: bigint): Evaluation {
  const operands = OPERATIONS[op].arity === 1 ? [a] : [a, b];
  if (operands.some((x) => x < 0n || x > UINT16_MAX)) {
    return { ok: false, reason: `operands must be whole numbers from 0 to ${UINT16_MAX}` };
  }
  let value: bigint;
  switch (op) {
    case "add":
      value = a + b;
      break;
    case "subtract":
      // Compact's Uint subtraction asserts "result of subtraction would be negative".
      if (b > a) return { ok: false, reason: "the result would be negative" };
      value = a - b;
      break;
    case "multiply":
      value = a * b;
      break;
    case "square":
      value = a * a;
      break;
    case "divide":
      // The divMod witness computes this with bigint `/`, which throws on 0,
      // and no quotient could satisfy the circuit's `rem < num2` check anyway.
      if (b === 0n) return { ok: false, reason: "cannot divide by zero" };
      // bigint `/` truncates, matching divMod's quotient.
      value = a / b;
      break;
  }
  // The `as Uint<16>` cast in add/multiply/square fails above 65535.
  if (value > UINT16_MAX) return { ok: false, reason: `the result would exceed ${UINT16_MAX}` };
  return { ok: true, value };
}

/** Parse a text field into a non-negative bigint; null if it isn't one. */
export function parseOperand(text: string): bigint | null {
  const t = text.trim();
  return /^\d+$/.test(t) ? BigInt(t) : null;
}

/**
 * Live view of the public ledger. The indexer pushes each new contract state
 * over its websocket, and the compiler-generated `ledger()` decodes it.
 */
export function ledger$(
  providers: CalculatorProviders,
  address: ContractAddress,
): Observable<Ledger> {
  return providers.publicDataProvider
    .contractStateObservable(address, { type: "latest" })
    .pipe(map((state) => ledger(state.data)));
}
