// This file is part of example-silent-auction.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file's main purpose is to export the compiled contract. The imports below
// resolve against contract/managed/silent-auction, which is generated by `yarn compile`
// (gitignored). Write contract/silent-auction.compact first, then compile.
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';

export {
  Contract,
  ledger,
  pureCircuits,
  type Witnesses,
  type Ledger,
  type ImpureCircuits,
  type PureCircuits,
} from './managed/silent-auction/contract/index.js';
import { Contract } from './managed/silent-auction/contract/index.js';
import { witnesses } from './witnesses.js';
const currentDir = path.resolve(new URL(import.meta.url).pathname, '..');
export const zkConfigPath = path.resolve(currentDir, 'managed', 'silent-auction');

export const CompiledSilentAuctionContract = CompiledContract.make(
  'SilentAuctionContract',
  Contract,
).pipe(
  // This contract declares witnesses (localSk / localSalt), so wire in their
  // implementations rather than the vacant (no-op) witness set.
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(zkConfigPath),
);
